// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportService.proto

package com.example.reports;

public final class ReportProto {
  private ReportProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ReportService.proto\"?\n\014EmailRequest\022\r\n" +
      "\005email\030\001 \001(\t\022\017\n\007subject\030\002 \001(\t\022\017\n\007message" +
      "\030\003 \001(\t\"1\n\rEmailResponse\022\017\n\007success\030\001 \001(\010" +
      "\022\017\n\007message\030\002 \001(\t2=\n\rReportService\022,\n\tSe" +
      "ndEmail\022\r.EmailRequest\032\016.EmailResponse\"\000" +
      "B$\n\023com.example.reportsB\013ReportProtoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EmailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EmailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmailRequest_descriptor,
        new java.lang.String[] { "Email", "Subject", "Message", });
    internal_static_EmailResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EmailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmailResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
