// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportService.proto

package com.example.reports;

public interface SessionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Session)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string bookingId = 3;</code>
   * @return The bookingId.
   */
  java.lang.String getBookingId();
  /**
   * <code>string bookingId = 3;</code>
   * @return The bytes for bookingId.
   */
  com.google.protobuf.ByteString
      getBookingIdBytes();
}
