// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentService.proto

package com.example.payment;

public final class PaymentProto {
  private PaymentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PaymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PaymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PaymentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PaymentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024PaymentService.proto\"h\n\016PaymentRequest" +
      "\022\025\n\rcustomer_name\030\001 \001(\t\022\032\n\022credit_card_n" +
      "umber\030\002 \001(\t\022\023\n\013expiry_date\030\003 \001(\t\022\016\n\006amou" +
      "nt\030\004 \001(\001\"3\n\017PaymentResponse\022\017\n\007success\030\001" +
      " \001(\010\022\017\n\007message\030\002 \001(\t2D\n\016PaymentService\022" +
      "2\n\013MakePayment\022\017.PaymentRequest\032\020.Paymen" +
      "tResponse\"\000B%\n\023com.example.paymentB\014Paym" +
      "entProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PaymentRequest_descriptor,
        new java.lang.String[] { "CustomerName", "CreditCardNumber", "ExpiryDate", "Amount", });
    internal_static_PaymentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PaymentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PaymentResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
