// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentService.proto

package com.example.payment;

public interface PaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string customer_name = 1;</code>
   * @return The customerName.
   */
  java.lang.String getCustomerName();
  /**
   * <code>string customer_name = 1;</code>
   * @return The bytes for customerName.
   */
  com.google.protobuf.ByteString
      getCustomerNameBytes();

  /**
   * <code>string credit_card_number = 2;</code>
   * @return The creditCardNumber.
   */
  java.lang.String getCreditCardNumber();
  /**
   * <code>string credit_card_number = 2;</code>
   * @return The bytes for creditCardNumber.
   */
  com.google.protobuf.ByteString
      getCreditCardNumberBytes();

  /**
   * <code>string expiry_date = 3;</code>
   * @return The expiryDate.
   */
  java.lang.String getExpiryDate();
  /**
   * <code>string expiry_date = 3;</code>
   * @return The bytes for expiryDate.
   */
  com.google.protobuf.ByteString
      getExpiryDateBytes();

  /**
   * <code>double amount = 4;</code>
   * @return The amount.
   */
  double getAmount();
}
