// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentService.proto

package com.example.payment;

public interface PaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string customer_name = 1;</code>
   * @return The customerName.
   */
  java.lang.String getCustomerName();
  /**
   * <code>string customer_name = 1;</code>
   * @return The bytes for customerName.
   */
  com.google.protobuf.ByteString
      getCustomerNameBytes();

  /**
   * <code>string card_number = 2;</code>
   * @return The cardNumber.
   */
  java.lang.String getCardNumber();
  /**
   * <code>string card_number = 2;</code>
   * @return The bytes for cardNumber.
   */
  com.google.protobuf.ByteString
      getCardNumberBytes();

  /**
   * <code>string expiry_date = 3;</code>
   * @return The expiryDate.
   */
  java.lang.String getExpiryDate();
  /**
   * <code>string expiry_date = 3;</code>
   * @return The bytes for expiryDate.
   */
  com.google.protobuf.ByteString
      getExpiryDateBytes();

  /**
   * <code>double amount = 4;</code>
   * @return The amount.
   */
  double getAmount();

  /**
   * <code>int32 booking_id = 5;</code>
   * @return The bookingId.
   */
  int getBookingId();

  /**
   * <code>string cvv = 6;</code>
   * @return The cvv.
   */
  java.lang.String getCvv();
  /**
   * <code>string cvv = 6;</code>
   * @return The bytes for cvv.
   */
  com.google.protobuf.ByteString
      getCvvBytes();
}
