// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingService.proto

package com.example.booking;

/**
 * Protobuf type {@code BookingRequest}
 */
public final class BookingRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BookingRequest)
    BookingRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BookingRequest.newBuilder() to construct.
  private BookingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BookingRequest() {
    customerName_ = "";
    pickupLocation_ = "";
    dropoffLocation_ = "";
    pickupDateTime_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BookingRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.booking.BookingProto.internal_static_BookingRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.booking.BookingProto.internal_static_BookingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.booking.BookingRequest.class, com.example.booking.BookingRequest.Builder.class);
  }

  public static final int CUSTOMER_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object customerName_ = "";
  /**
   * <code>string customer_name = 1;</code>
   * @return The customerName.
   */
  @java.lang.Override
  public java.lang.String getCustomerName() {
    java.lang.Object ref = customerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      customerName_ = s;
      return s;
    }
  }
  /**
   * <code>string customer_name = 1;</code>
   * @return The bytes for customerName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCustomerNameBytes() {
    java.lang.Object ref = customerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      customerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PICKUP_LOCATION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pickupLocation_ = "";
  /**
   * <code>string pickup_location = 2;</code>
   * @return The pickupLocation.
   */
  @java.lang.Override
  public java.lang.String getPickupLocation() {
    java.lang.Object ref = pickupLocation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pickupLocation_ = s;
      return s;
    }
  }
  /**
   * <code>string pickup_location = 2;</code>
   * @return The bytes for pickupLocation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPickupLocationBytes() {
    java.lang.Object ref = pickupLocation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pickupLocation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DROPOFF_LOCATION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dropoffLocation_ = "";
  /**
   * <code>string dropoff_location = 3;</code>
   * @return The dropoffLocation.
   */
  @java.lang.Override
  public java.lang.String getDropoffLocation() {
    java.lang.Object ref = dropoffLocation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dropoffLocation_ = s;
      return s;
    }
  }
  /**
   * <code>string dropoff_location = 3;</code>
   * @return The bytes for dropoffLocation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDropoffLocationBytes() {
    java.lang.Object ref = dropoffLocation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dropoffLocation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PICKUP_DATE_TIME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pickupDateTime_ = "";
  /**
   * <code>string pickup_date_time = 4;</code>
   * @return The pickupDateTime.
   */
  @java.lang.Override
  public java.lang.String getPickupDateTime() {
    java.lang.Object ref = pickupDateTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pickupDateTime_ = s;
      return s;
    }
  }
  /**
   * <code>string pickup_date_time = 4;</code>
   * @return The bytes for pickupDateTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPickupDateTimeBytes() {
    java.lang.Object ref = pickupDateTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pickupDateTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, customerName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pickupLocation_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pickupLocation_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dropoffLocation_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dropoffLocation_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pickupDateTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, pickupDateTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, customerName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pickupLocation_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pickupLocation_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dropoffLocation_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dropoffLocation_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pickupDateTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, pickupDateTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.booking.BookingRequest)) {
      return super.equals(obj);
    }
    com.example.booking.BookingRequest other = (com.example.booking.BookingRequest) obj;

    if (!getCustomerName()
        .equals(other.getCustomerName())) return false;
    if (!getPickupLocation()
        .equals(other.getPickupLocation())) return false;
    if (!getDropoffLocation()
        .equals(other.getDropoffLocation())) return false;
    if (!getPickupDateTime()
        .equals(other.getPickupDateTime())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CUSTOMER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getCustomerName().hashCode();
    hash = (37 * hash) + PICKUP_LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getPickupLocation().hashCode();
    hash = (37 * hash) + DROPOFF_LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getDropoffLocation().hashCode();
    hash = (37 * hash) + PICKUP_DATE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getPickupDateTime().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.booking.BookingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.booking.BookingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.booking.BookingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.booking.BookingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.booking.BookingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.booking.BookingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.booking.BookingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.booking.BookingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.booking.BookingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.booking.BookingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.booking.BookingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.booking.BookingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.booking.BookingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BookingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BookingRequest)
      com.example.booking.BookingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.booking.BookingProto.internal_static_BookingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.booking.BookingProto.internal_static_BookingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.booking.BookingRequest.class, com.example.booking.BookingRequest.Builder.class);
    }

    // Construct using com.example.booking.BookingRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      customerName_ = "";
      pickupLocation_ = "";
      dropoffLocation_ = "";
      pickupDateTime_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.booking.BookingProto.internal_static_BookingRequest_descriptor;
    }

    @java.lang.Override
    public com.example.booking.BookingRequest getDefaultInstanceForType() {
      return com.example.booking.BookingRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.booking.BookingRequest build() {
      com.example.booking.BookingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.booking.BookingRequest buildPartial() {
      com.example.booking.BookingRequest result = new com.example.booking.BookingRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.booking.BookingRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.customerName_ = customerName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pickupLocation_ = pickupLocation_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.dropoffLocation_ = dropoffLocation_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.pickupDateTime_ = pickupDateTime_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.booking.BookingRequest) {
        return mergeFrom((com.example.booking.BookingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.booking.BookingRequest other) {
      if (other == com.example.booking.BookingRequest.getDefaultInstance()) return this;
      if (!other.getCustomerName().isEmpty()) {
        customerName_ = other.customerName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getPickupLocation().isEmpty()) {
        pickupLocation_ = other.pickupLocation_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getDropoffLocation().isEmpty()) {
        dropoffLocation_ = other.dropoffLocation_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getPickupDateTime().isEmpty()) {
        pickupDateTime_ = other.pickupDateTime_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              customerName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              pickupLocation_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              dropoffLocation_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              pickupDateTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object customerName_ = "";
    /**
     * <code>string customer_name = 1;</code>
     * @return The customerName.
     */
    public java.lang.String getCustomerName() {
      java.lang.Object ref = customerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string customer_name = 1;</code>
     * @return The bytes for customerName.
     */
    public com.google.protobuf.ByteString
        getCustomerNameBytes() {
      java.lang.Object ref = customerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string customer_name = 1;</code>
     * @param value The customerName to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      customerName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string customer_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerName() {
      customerName_ = getDefaultInstance().getCustomerName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string customer_name = 1;</code>
     * @param value The bytes for customerName to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      customerName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object pickupLocation_ = "";
    /**
     * <code>string pickup_location = 2;</code>
     * @return The pickupLocation.
     */
    public java.lang.String getPickupLocation() {
      java.lang.Object ref = pickupLocation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pickupLocation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pickup_location = 2;</code>
     * @return The bytes for pickupLocation.
     */
    public com.google.protobuf.ByteString
        getPickupLocationBytes() {
      java.lang.Object ref = pickupLocation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pickupLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pickup_location = 2;</code>
     * @param value The pickupLocation to set.
     * @return This builder for chaining.
     */
    public Builder setPickupLocation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pickupLocation_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string pickup_location = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPickupLocation() {
      pickupLocation_ = getDefaultInstance().getPickupLocation();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string pickup_location = 2;</code>
     * @param value The bytes for pickupLocation to set.
     * @return This builder for chaining.
     */
    public Builder setPickupLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pickupLocation_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object dropoffLocation_ = "";
    /**
     * <code>string dropoff_location = 3;</code>
     * @return The dropoffLocation.
     */
    public java.lang.String getDropoffLocation() {
      java.lang.Object ref = dropoffLocation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dropoffLocation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dropoff_location = 3;</code>
     * @return The bytes for dropoffLocation.
     */
    public com.google.protobuf.ByteString
        getDropoffLocationBytes() {
      java.lang.Object ref = dropoffLocation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dropoffLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dropoff_location = 3;</code>
     * @param value The dropoffLocation to set.
     * @return This builder for chaining.
     */
    public Builder setDropoffLocation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dropoffLocation_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string dropoff_location = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDropoffLocation() {
      dropoffLocation_ = getDefaultInstance().getDropoffLocation();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string dropoff_location = 3;</code>
     * @param value The bytes for dropoffLocation to set.
     * @return This builder for chaining.
     */
    public Builder setDropoffLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dropoffLocation_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object pickupDateTime_ = "";
    /**
     * <code>string pickup_date_time = 4;</code>
     * @return The pickupDateTime.
     */
    public java.lang.String getPickupDateTime() {
      java.lang.Object ref = pickupDateTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pickupDateTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pickup_date_time = 4;</code>
     * @return The bytes for pickupDateTime.
     */
    public com.google.protobuf.ByteString
        getPickupDateTimeBytes() {
      java.lang.Object ref = pickupDateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pickupDateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pickup_date_time = 4;</code>
     * @param value The pickupDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setPickupDateTime(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pickupDateTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string pickup_date_time = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPickupDateTime() {
      pickupDateTime_ = getDefaultInstance().getPickupDateTime();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string pickup_date_time = 4;</code>
     * @param value The bytes for pickupDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setPickupDateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pickupDateTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BookingRequest)
  }

  // @@protoc_insertion_point(class_scope:BookingRequest)
  private static final com.example.booking.BookingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.booking.BookingRequest();
  }

  public static com.example.booking.BookingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BookingRequest>
      PARSER = new com.google.protobuf.AbstractParser<BookingRequest>() {
    @java.lang.Override
    public BookingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BookingRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BookingRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.booking.BookingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

