//updates in 16/04

// Generated by the protocol buffer compiler
// source: booking.proto

package com.examples.booking;

public final class BookingServiceImpl {
  private BookingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_PersonalData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_PersonalData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_ReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_ReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_ReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_ReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_PaymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_PaymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_PaymentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_PaymentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbooking.proto\022\005maths\"9\n\014PersonalData\022\014" +
      "\n\004name\030\001 \001(\t\022\014\n\004pone\030\002 \001(\005\022\r\n\005email\030\003 \001(" +
      "\t\"/\n\020RegisterResponse\022\n\n\002id\030\001 \001(\t\022\017\n\007mes" +
      "sage\030\002 \001(\t\"f\n\022ReservationRequest\022\017\n\007gues" +
      "tId\030\001 \001(\005\022\033\n\023paymentConfirmation\030\002 \001(\t\022\021" +
      "\n\tstartDate\030\003 \001(\t\022\017\n\007endDate\030\004 \001(\t\"6\n\023Re" +
      "servationResponse\022\016\n\006status\030\001 \001(\005\022\017\n\007mes" +
      "sage\030\002 \001(\t\"\250\001\n\016PaymentRequest\022\017\n\007guestId" +
      "\030\001 \001(\005\022\025\n\rreservationId\030\003 \001(\005\0223\n\rpayment" +
      "Method\030\004 \001(\0162\034.maths.PaymentRequest.Meth" +
      "od\"9\n\006Method\022\020\n\014MOBILE_MONEY\020\000\022\010\n\004CARD\020\001" +
      "\022\007\n\003RTS\020\002\022\n\n\006PAYPAL\020\003\"2\n\017PaymentResponse" +
      "\022\016\n\006status\030\001 \001(\005\022\017\n\007message\030\002 \001(\t2\332\001\n\007Bo" +
      "oking\022A\n\013createGuest\022\023.maths.PersonalDat" +
      "a\032\027.maths.RegisterResponse\"\000(\0010\001\022L\n\017book" +
      "Reservation\022\031.maths.ReservationRequest\032\032" +
      ".maths.ReservationResponse\"\0000\001\022>\n\013makePa" +
      "yment\022\025.maths.PaymentRequest\032\026.maths.Pay" +
      "mentResponse\"\000B,\n\024com.examples.bookingB\022" +
      "BookingServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_maths_PersonalData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maths_PersonalData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_PersonalData_descriptor,
        new java.lang.String[] { "Name", "Pone", "Email", });
    internal_static_maths_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_maths_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_RegisterResponse_descriptor,
        new java.lang.String[] { "Id", "Message", });
    internal_static_maths_ReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_maths_ReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_ReservationRequest_descriptor,
        new java.lang.String[] { "GuestId", "PaymentConfirmation", "StartDate", "EndDate", });
    internal_static_maths_ReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_maths_ReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_ReservationResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_maths_PaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_maths_PaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_PaymentRequest_descriptor,
        new java.lang.String[] { "GuestId", "ReservationId", "PaymentMethod", });
    internal_static_maths_PaymentResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_maths_PaymentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_PaymentResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
