// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingService.proto

package com.example.booking;

public interface BookingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Booking)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string booking_id = 1;</code>
   * @return The bookingId.
   */
  java.lang.String getBookingId();
  /**
   * <code>string booking_id = 1;</code>
   * @return The bytes for bookingId.
   */
  com.google.protobuf.ByteString
      getBookingIdBytes();

  /**
   * <code>string customer_name = 2;</code>
   * @return The customerName.
   */
  java.lang.String getCustomerName();
  /**
   * <code>string customer_name = 2;</code>
   * @return The bytes for customerName.
   */
  com.google.protobuf.ByteString
      getCustomerNameBytes();

  /**
   * <code>string pickup_location = 3;</code>
   * @return The pickupLocation.
   */
  java.lang.String getPickupLocation();
  /**
   * <code>string pickup_location = 3;</code>
   * @return The bytes for pickupLocation.
   */
  com.google.protobuf.ByteString
      getPickupLocationBytes();

  /**
   * <code>string dropoff_location = 4;</code>
   * @return The dropoffLocation.
   */
  java.lang.String getDropoffLocation();
  /**
   * <code>string dropoff_location = 4;</code>
   * @return The bytes for dropoffLocation.
   */
  com.google.protobuf.ByteString
      getDropoffLocationBytes();

  /**
   * <code>string pickup_date_time = 5;</code>
   * @return The pickupDateTime.
   */
  java.lang.String getPickupDateTime();
  /**
   * <code>string pickup_date_time = 5;</code>
   * @return The bytes for pickupDateTime.
   */
  com.google.protobuf.ByteString
      getPickupDateTimeBytes();
}
