// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingService.proto

package com.example.booking;

public interface GetBookingsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetBookingsRequest)
    com.google.protobuf.MessageOrBuilder {
}
