// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingService.proto

package com.example.booking;

/**
 * Protobuf type {@code GetBookingsResponse}
 */
public final class GetBookingsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetBookingsResponse)
    GetBookingsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetBookingsResponse.newBuilder() to construct.
  private GetBookingsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetBookingsResponse() {
    bookings_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetBookingsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.booking.BookingProto.internal_static_GetBookingsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.booking.BookingProto.internal_static_GetBookingsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.booking.GetBookingsResponse.class, com.example.booking.GetBookingsResponse.Builder.class);
  }

  public static final int BOOKINGS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.example.booking.Booking> bookings_;
  /**
   * <code>repeated .Booking bookings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.booking.Booking> getBookingsList() {
    return bookings_;
  }
  /**
   * <code>repeated .Booking bookings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.booking.BookingOrBuilder> 
      getBookingsOrBuilderList() {
    return bookings_;
  }
  /**
   * <code>repeated .Booking bookings = 1;</code>
   */
  @java.lang.Override
  public int getBookingsCount() {
    return bookings_.size();
  }
  /**
   * <code>repeated .Booking bookings = 1;</code>
   */
  @java.lang.Override
  public com.example.booking.Booking getBookings(int index) {
    return bookings_.get(index);
  }
  /**
   * <code>repeated .Booking bookings = 1;</code>
   */
  @java.lang.Override
  public com.example.booking.BookingOrBuilder getBookingsOrBuilder(
      int index) {
    return bookings_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < bookings_.size(); i++) {
      output.writeMessage(1, bookings_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < bookings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, bookings_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.booking.GetBookingsResponse)) {
      return super.equals(obj);
    }
    com.example.booking.GetBookingsResponse other = (com.example.booking.GetBookingsResponse) obj;

    if (!getBookingsList()
        .equals(other.getBookingsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBookingsCount() > 0) {
      hash = (37 * hash) + BOOKINGS_FIELD_NUMBER;
      hash = (53 * hash) + getBookingsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.booking.GetBookingsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.booking.GetBookingsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.booking.GetBookingsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.booking.GetBookingsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.booking.GetBookingsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.booking.GetBookingsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.booking.GetBookingsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.booking.GetBookingsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.booking.GetBookingsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.booking.GetBookingsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.booking.GetBookingsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.booking.GetBookingsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.booking.GetBookingsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetBookingsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetBookingsResponse)
      com.example.booking.GetBookingsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.booking.BookingProto.internal_static_GetBookingsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.booking.BookingProto.internal_static_GetBookingsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.booking.GetBookingsResponse.class, com.example.booking.GetBookingsResponse.Builder.class);
    }

    // Construct using com.example.booking.GetBookingsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (bookingsBuilder_ == null) {
        bookings_ = java.util.Collections.emptyList();
      } else {
        bookings_ = null;
        bookingsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.booking.BookingProto.internal_static_GetBookingsResponse_descriptor;
    }

    @java.lang.Override
    public com.example.booking.GetBookingsResponse getDefaultInstanceForType() {
      return com.example.booking.GetBookingsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.booking.GetBookingsResponse build() {
      com.example.booking.GetBookingsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.booking.GetBookingsResponse buildPartial() {
      com.example.booking.GetBookingsResponse result = new com.example.booking.GetBookingsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.example.booking.GetBookingsResponse result) {
      if (bookingsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          bookings_ = java.util.Collections.unmodifiableList(bookings_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.bookings_ = bookings_;
      } else {
        result.bookings_ = bookingsBuilder_.build();
      }
    }

    private void buildPartial0(com.example.booking.GetBookingsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.booking.GetBookingsResponse) {
        return mergeFrom((com.example.booking.GetBookingsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.booking.GetBookingsResponse other) {
      if (other == com.example.booking.GetBookingsResponse.getDefaultInstance()) return this;
      if (bookingsBuilder_ == null) {
        if (!other.bookings_.isEmpty()) {
          if (bookings_.isEmpty()) {
            bookings_ = other.bookings_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBookingsIsMutable();
            bookings_.addAll(other.bookings_);
          }
          onChanged();
        }
      } else {
        if (!other.bookings_.isEmpty()) {
          if (bookingsBuilder_.isEmpty()) {
            bookingsBuilder_.dispose();
            bookingsBuilder_ = null;
            bookings_ = other.bookings_;
            bitField0_ = (bitField0_ & ~0x00000001);
            bookingsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBookingsFieldBuilder() : null;
          } else {
            bookingsBuilder_.addAllMessages(other.bookings_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.example.booking.Booking m =
                  input.readMessage(
                      com.example.booking.Booking.parser(),
                      extensionRegistry);
              if (bookingsBuilder_ == null) {
                ensureBookingsIsMutable();
                bookings_.add(m);
              } else {
                bookingsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.booking.Booking> bookings_ =
      java.util.Collections.emptyList();
    private void ensureBookingsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        bookings_ = new java.util.ArrayList<com.example.booking.Booking>(bookings_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.booking.Booking, com.example.booking.Booking.Builder, com.example.booking.BookingOrBuilder> bookingsBuilder_;

    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public java.util.List<com.example.booking.Booking> getBookingsList() {
      if (bookingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bookings_);
      } else {
        return bookingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public int getBookingsCount() {
      if (bookingsBuilder_ == null) {
        return bookings_.size();
      } else {
        return bookingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public com.example.booking.Booking getBookings(int index) {
      if (bookingsBuilder_ == null) {
        return bookings_.get(index);
      } else {
        return bookingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public Builder setBookings(
        int index, com.example.booking.Booking value) {
      if (bookingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookingsIsMutable();
        bookings_.set(index, value);
        onChanged();
      } else {
        bookingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public Builder setBookings(
        int index, com.example.booking.Booking.Builder builderForValue) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.set(index, builderForValue.build());
        onChanged();
      } else {
        bookingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public Builder addBookings(com.example.booking.Booking value) {
      if (bookingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookingsIsMutable();
        bookings_.add(value);
        onChanged();
      } else {
        bookingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public Builder addBookings(
        int index, com.example.booking.Booking value) {
      if (bookingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookingsIsMutable();
        bookings_.add(index, value);
        onChanged();
      } else {
        bookingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public Builder addBookings(
        com.example.booking.Booking.Builder builderForValue) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.add(builderForValue.build());
        onChanged();
      } else {
        bookingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public Builder addBookings(
        int index, com.example.booking.Booking.Builder builderForValue) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.add(index, builderForValue.build());
        onChanged();
      } else {
        bookingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public Builder addAllBookings(
        java.lang.Iterable<? extends com.example.booking.Booking> values) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bookings_);
        onChanged();
      } else {
        bookingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public Builder clearBookings() {
      if (bookingsBuilder_ == null) {
        bookings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        bookingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public Builder removeBookings(int index) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.remove(index);
        onChanged();
      } else {
        bookingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public com.example.booking.Booking.Builder getBookingsBuilder(
        int index) {
      return getBookingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public com.example.booking.BookingOrBuilder getBookingsOrBuilder(
        int index) {
      if (bookingsBuilder_ == null) {
        return bookings_.get(index);  } else {
        return bookingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public java.util.List<? extends com.example.booking.BookingOrBuilder> 
         getBookingsOrBuilderList() {
      if (bookingsBuilder_ != null) {
        return bookingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bookings_);
      }
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public com.example.booking.Booking.Builder addBookingsBuilder() {
      return getBookingsFieldBuilder().addBuilder(
          com.example.booking.Booking.getDefaultInstance());
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public com.example.booking.Booking.Builder addBookingsBuilder(
        int index) {
      return getBookingsFieldBuilder().addBuilder(
          index, com.example.booking.Booking.getDefaultInstance());
    }
    /**
     * <code>repeated .Booking bookings = 1;</code>
     */
    public java.util.List<com.example.booking.Booking.Builder> 
         getBookingsBuilderList() {
      return getBookingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.booking.Booking, com.example.booking.Booking.Builder, com.example.booking.BookingOrBuilder> 
        getBookingsFieldBuilder() {
      if (bookingsBuilder_ == null) {
        bookingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.booking.Booking, com.example.booking.Booking.Builder, com.example.booking.BookingOrBuilder>(
                bookings_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        bookings_ = null;
      }
      return bookingsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetBookingsResponse)
  }

  // @@protoc_insertion_point(class_scope:GetBookingsResponse)
  private static final com.example.booking.GetBookingsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.booking.GetBookingsResponse();
  }

  public static com.example.booking.GetBookingsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetBookingsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetBookingsResponse>() {
    @java.lang.Override
    public GetBookingsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetBookingsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetBookingsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.booking.GetBookingsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

