// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package com.examples.booking;

public interface RegisterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maths.RegisterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
