// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingService.proto

package com.example.booking;

public final class BookingProto {
  private BookingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Booking_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Booking_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetBookingsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetBookingsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetBookingsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetBookingsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024BookingService.proto\"t\n\016BookingRequest" +
      "\022\025\n\rcustomer_name\030\001 \001(\t\022\027\n\017pickup_locati" +
      "on\030\002 \001(\t\022\030\n\020dropoff_location\030\003 \001(\t\022\030\n\020pi" +
      "ckup_date_time\030\004 \001(\t\";\n\017BookingResponse\022" +
      "\022\n\nbooking_id\030\001 \001(\t\022\024\n\014confirmation\030\002 \001(" +
      "\t\"\201\001\n\007Booking\022\022\n\nbooking_id\030\001 \001(\t\022\025\n\rcus" +
      "tomer_name\030\002 \001(\t\022\027\n\017pickup_location\030\003 \001(" +
      "\t\022\030\n\020dropoff_location\030\004 \001(\t\022\030\n\020pickup_da" +
      "te_time\030\005 \001(\t\"\024\n\022GetBookingsRequest\"1\n\023G" +
      "etBookingsResponse\022\032\n\010bookings\030\001 \003(\0132\010.B" +
      "ooking2\200\001\n\016BookingService\0222\n\013MakeBooking" +
      "\022\017.BookingRequest\032\020.BookingResponse\"\000\022:\n" +
      "\013GetBookings\022\023.GetBookingsRequest\032\024.GetB" +
      "ookingsResponse\"\000B%\n\023com.example.booking" +
      "B\014BookingProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BookingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BookingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookingRequest_descriptor,
        new java.lang.String[] { "CustomerName", "PickupLocation", "DropoffLocation", "PickupDateTime", });
    internal_static_BookingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BookingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookingResponse_descriptor,
        new java.lang.String[] { "BookingId", "Confirmation", });
    internal_static_Booking_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Booking_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Booking_descriptor,
        new java.lang.String[] { "BookingId", "CustomerName", "PickupLocation", "DropoffLocation", "PickupDateTime", });
    internal_static_GetBookingsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetBookingsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetBookingsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetBookingsResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetBookingsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetBookingsResponse_descriptor,
        new java.lang.String[] { "Bookings", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
