// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingService.proto

package com.example.booking;

public interface BookingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string booking_id = 1;</code>
   * @return The bookingId.
   */
  java.lang.String getBookingId();
  /**
   * <code>string booking_id = 1;</code>
   * @return The bytes for bookingId.
   */
  com.google.protobuf.ByteString
      getBookingIdBytes();

  /**
   * <code>string confirmation = 2;</code>
   * @return The confirmation.
   */
  java.lang.String getConfirmation();
  /**
   * <code>string confirmation = 2;</code>
   * @return The bytes for confirmation.
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();
}
