// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingService.proto

package com.example.booking;

public interface GetRoomsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetRoomsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bookings = 1;</code>
   * @return The bookings.
   */
  java.lang.String getBookings();
  /**
   * <code>string bookings = 1;</code>
   * @return The bytes for bookings.
   */
  com.google.protobuf.ByteString
      getBookingsBytes();
}
