// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingService.proto

package com.example.booking;

/**
 * Protobuf type {@code GetRoomsResponse}
 */
public final class GetRoomsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetRoomsResponse)
    GetRoomsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetRoomsResponse.newBuilder() to construct.
  private GetRoomsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetRoomsResponse() {
    rooms_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetRoomsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.booking.BookingProto.internal_static_GetRoomsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.booking.BookingProto.internal_static_GetRoomsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.booking.GetRoomsResponse.class, com.example.booking.GetRoomsResponse.Builder.class);
  }

  public static final int ROOMS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.example.booking.Room> rooms_;
  /**
   * <code>repeated .Room rooms = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.booking.Room> getRoomsList() {
    return rooms_;
  }
  /**
   * <code>repeated .Room rooms = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.booking.RoomOrBuilder> 
      getRoomsOrBuilderList() {
    return rooms_;
  }
  /**
   * <code>repeated .Room rooms = 1;</code>
   */
  @java.lang.Override
  public int getRoomsCount() {
    return rooms_.size();
  }
  /**
   * <code>repeated .Room rooms = 1;</code>
   */
  @java.lang.Override
  public com.example.booking.Room getRooms(int index) {
    return rooms_.get(index);
  }
  /**
   * <code>repeated .Room rooms = 1;</code>
   */
  @java.lang.Override
  public com.example.booking.RoomOrBuilder getRoomsOrBuilder(
      int index) {
    return rooms_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < rooms_.size(); i++) {
      output.writeMessage(1, rooms_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < rooms_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, rooms_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.booking.GetRoomsResponse)) {
      return super.equals(obj);
    }
    com.example.booking.GetRoomsResponse other = (com.example.booking.GetRoomsResponse) obj;

    if (!getRoomsList()
        .equals(other.getRoomsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRoomsCount() > 0) {
      hash = (37 * hash) + ROOMS_FIELD_NUMBER;
      hash = (53 * hash) + getRoomsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.booking.GetRoomsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.booking.GetRoomsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.booking.GetRoomsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.booking.GetRoomsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.booking.GetRoomsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.booking.GetRoomsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.booking.GetRoomsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.booking.GetRoomsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.booking.GetRoomsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.booking.GetRoomsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.booking.GetRoomsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.booking.GetRoomsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.booking.GetRoomsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetRoomsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetRoomsResponse)
      com.example.booking.GetRoomsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.booking.BookingProto.internal_static_GetRoomsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.booking.BookingProto.internal_static_GetRoomsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.booking.GetRoomsResponse.class, com.example.booking.GetRoomsResponse.Builder.class);
    }

    // Construct using com.example.booking.GetRoomsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (roomsBuilder_ == null) {
        rooms_ = java.util.Collections.emptyList();
      } else {
        rooms_ = null;
        roomsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.booking.BookingProto.internal_static_GetRoomsResponse_descriptor;
    }

    @java.lang.Override
    public com.example.booking.GetRoomsResponse getDefaultInstanceForType() {
      return com.example.booking.GetRoomsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.booking.GetRoomsResponse build() {
      com.example.booking.GetRoomsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.booking.GetRoomsResponse buildPartial() {
      com.example.booking.GetRoomsResponse result = new com.example.booking.GetRoomsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.example.booking.GetRoomsResponse result) {
      if (roomsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          rooms_ = java.util.Collections.unmodifiableList(rooms_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rooms_ = rooms_;
      } else {
        result.rooms_ = roomsBuilder_.build();
      }
    }

    private void buildPartial0(com.example.booking.GetRoomsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.booking.GetRoomsResponse) {
        return mergeFrom((com.example.booking.GetRoomsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.booking.GetRoomsResponse other) {
      if (other == com.example.booking.GetRoomsResponse.getDefaultInstance()) return this;
      if (roomsBuilder_ == null) {
        if (!other.rooms_.isEmpty()) {
          if (rooms_.isEmpty()) {
            rooms_ = other.rooms_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRoomsIsMutable();
            rooms_.addAll(other.rooms_);
          }
          onChanged();
        }
      } else {
        if (!other.rooms_.isEmpty()) {
          if (roomsBuilder_.isEmpty()) {
            roomsBuilder_.dispose();
            roomsBuilder_ = null;
            rooms_ = other.rooms_;
            bitField0_ = (bitField0_ & ~0x00000001);
            roomsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRoomsFieldBuilder() : null;
          } else {
            roomsBuilder_.addAllMessages(other.rooms_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.example.booking.Room m =
                  input.readMessage(
                      com.example.booking.Room.parser(),
                      extensionRegistry);
              if (roomsBuilder_ == null) {
                ensureRoomsIsMutable();
                rooms_.add(m);
              } else {
                roomsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.booking.Room> rooms_ =
      java.util.Collections.emptyList();
    private void ensureRoomsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        rooms_ = new java.util.ArrayList<com.example.booking.Room>(rooms_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.booking.Room, com.example.booking.Room.Builder, com.example.booking.RoomOrBuilder> roomsBuilder_;

    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public java.util.List<com.example.booking.Room> getRoomsList() {
      if (roomsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rooms_);
      } else {
        return roomsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public int getRoomsCount() {
      if (roomsBuilder_ == null) {
        return rooms_.size();
      } else {
        return roomsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public com.example.booking.Room getRooms(int index) {
      if (roomsBuilder_ == null) {
        return rooms_.get(index);
      } else {
        return roomsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public Builder setRooms(
        int index, com.example.booking.Room value) {
      if (roomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomsIsMutable();
        rooms_.set(index, value);
        onChanged();
      } else {
        roomsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public Builder setRooms(
        int index, com.example.booking.Room.Builder builderForValue) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.set(index, builderForValue.build());
        onChanged();
      } else {
        roomsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public Builder addRooms(com.example.booking.Room value) {
      if (roomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomsIsMutable();
        rooms_.add(value);
        onChanged();
      } else {
        roomsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public Builder addRooms(
        int index, com.example.booking.Room value) {
      if (roomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomsIsMutable();
        rooms_.add(index, value);
        onChanged();
      } else {
        roomsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public Builder addRooms(
        com.example.booking.Room.Builder builderForValue) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.add(builderForValue.build());
        onChanged();
      } else {
        roomsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public Builder addRooms(
        int index, com.example.booking.Room.Builder builderForValue) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.add(index, builderForValue.build());
        onChanged();
      } else {
        roomsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public Builder addAllRooms(
        java.lang.Iterable<? extends com.example.booking.Room> values) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rooms_);
        onChanged();
      } else {
        roomsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public Builder clearRooms() {
      if (roomsBuilder_ == null) {
        rooms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        roomsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public Builder removeRooms(int index) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.remove(index);
        onChanged();
      } else {
        roomsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public com.example.booking.Room.Builder getRoomsBuilder(
        int index) {
      return getRoomsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public com.example.booking.RoomOrBuilder getRoomsOrBuilder(
        int index) {
      if (roomsBuilder_ == null) {
        return rooms_.get(index);  } else {
        return roomsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public java.util.List<? extends com.example.booking.RoomOrBuilder> 
         getRoomsOrBuilderList() {
      if (roomsBuilder_ != null) {
        return roomsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rooms_);
      }
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public com.example.booking.Room.Builder addRoomsBuilder() {
      return getRoomsFieldBuilder().addBuilder(
          com.example.booking.Room.getDefaultInstance());
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public com.example.booking.Room.Builder addRoomsBuilder(
        int index) {
      return getRoomsFieldBuilder().addBuilder(
          index, com.example.booking.Room.getDefaultInstance());
    }
    /**
     * <code>repeated .Room rooms = 1;</code>
     */
    public java.util.List<com.example.booking.Room.Builder> 
         getRoomsBuilderList() {
      return getRoomsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.booking.Room, com.example.booking.Room.Builder, com.example.booking.RoomOrBuilder> 
        getRoomsFieldBuilder() {
      if (roomsBuilder_ == null) {
        roomsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.booking.Room, com.example.booking.Room.Builder, com.example.booking.RoomOrBuilder>(
                rooms_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        rooms_ = null;
      }
      return roomsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetRoomsResponse)
  }

  // @@protoc_insertion_point(class_scope:GetRoomsResponse)
  private static final com.example.booking.GetRoomsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.booking.GetRoomsResponse();
  }

  public static com.example.booking.GetRoomsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetRoomsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetRoomsResponse>() {
    @java.lang.Override
    public GetRoomsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetRoomsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetRoomsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.booking.GetRoomsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

