// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingService.proto

package com.example.booking;

public interface RoomOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Room)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string room_number = 1;</code>
   * @return The roomNumber.
   */
  java.lang.String getRoomNumber();
  /**
   * <code>string room_number = 1;</code>
   * @return The bytes for roomNumber.
   */
  com.google.protobuf.ByteString
      getRoomNumberBytes();

  /**
   * <code>string room_name = 2;</code>
   * @return The roomName.
   */
  java.lang.String getRoomName();
  /**
   * <code>string room_name = 2;</code>
   * @return The bytes for roomName.
   */
  com.google.protobuf.ByteString
      getRoomNameBytes();

  /**
   * <code>string availability = 3;</code>
   * @return The availability.
   */
  java.lang.String getAvailability();
  /**
   * <code>string availability = 3;</code>
   * @return The bytes for availability.
   */
  com.google.protobuf.ByteString
      getAvailabilityBytes();

  /**
   * <code>double amount = 4;</code>
   * @return The amount.
   */
  double getAmount();
}
